services:
  portainer:
    image: portainer/portainer-ce

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.5
  
  metabase:
    image: metabase/metabase:latest

  identitydb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  feeddb:
    image: mongo
  
  chatdb:
    image: mongo

  embeddingmodel:
    image: ${DOCKER_REGISTRY-}embeddingmodel
    build:
      context: .
      dockerfile: Services/Recommendation/EmbeddingModel/Dockerfile
  
  recommendation.api:
    image: ${DOCKER_REGISTRY-}recommendationapi
    build:
      context: .
      dockerfile: Services/Recommendation/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  feed.api:
    image: ${DOCKER_REGISTRY-}feedapi
    build:
      context: .
      dockerfile: Services/Feed/Feed.API/Dockerfile

  chat.api:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: Services/Chat/Chat.API/Dockerfile

  ocelotapigw:
     image: ocelotapigw
     build:
        context: .
        dockerfile: ApiGateways/Ocelot.Apigateway/Dockerfile

volumes:
  chat_mongo_data:
  mongo_data:
  sqlserver_data:
  portainer_data:
  metabase_data:
  weaviate_data:  