services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - 8081:8000
      - 9090:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama'
      CLUSTER_HOSTNAME: 'node1'

  metabase:
    container_name: metabase
    restart: always
    hostname: metabase
    ports:
      - 9002:3000
    depends_on:
      - feeddb
    volumes:
      - metabase_data:/metabase-data

  identitydb:
    container_name: identitydb
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=YourSecurePassword123
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/data/db
  
  feeddb:
    container_name: feeddb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  chatdb:
    container_name: chatdb
    restart: always
    ports:
      - 27018:27017
    volumes:
      - chat_mongo_data:/data/db
  
  embeddingmodel:
    container_name: embeddingmodel
    restart: always
    ports:
      - 11435:11434

  recommendation.api:
    container_name: recommendation.api
    restart: always
    ports:
      - 9003:80
    environment:
      - NODE_ENV=production
      - PORT=80
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
      - EMBEDDING_MODEL_URL=http://embeddingmodel:11434
      - FEED_SERVICE=http://feed.api
      - GOOGLE_API_KEY=AIzaSyC_TIXs1O6Xi-bi6WRGISvrlcAxxl46Cgo
    depends_on:
      - weaviate
      - embeddingmodel

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - DatabaseSettings__ConnectionString=Server=identitydb;Database=IdentityDb;User Id=sa;Password=YourSecurePassword123;TrustServerCertificate=True;
    depends_on:
      - identitydb
    ports:
      - "9020:80"
  
  feed.api:
    container_name: feed.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - DatabaseSettings__ConnectionString=mongodb://feeddb:27017
      - DatabaseSettings__DatabaseName=FeedDb
      - DatabaseSettings__PostsCollection=Posts
      - DatabaseSettings__SavedPostsCollection=SavedPosts
      - DatabaseSettings__ReportsCollection=Reports
      - DatabaseSettings__UserReactionsCollection=UserReactions
      - DatabaseSettings__UserCommentsCollection=UserComments
      - DatabaseSettings__UserSharesCollection=UserShares
      - Microservices__Identity__BaseUrl=http://identity.api/api/v1/
      - Microservices__Recommendation__BaseUrl=http://recommendation.api/
    depends_on:
      - feeddb
    ports:
      - "9000:80"

  chat.api:
    container_name: chat.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - DatabaseSettings__ConnectionString=mongodb://chatdb:27017
      - DatabaseSettings__DatabaseName=ChatDb
      - DatabaseSettings__ChatRoomCollection=ChatRooms
      - DatabaseSettings__MessageCollection=Messages
      - Microservices__Identity__BaseUrl=http://identity.api/api/v1/
      - Microservices__Feed__BaseUrl=http://feed.api/api/v1/
    depends_on:
      - chatdb
    ports:
      - "9001:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - identity.api
      - feed.api
    ports:
      - 9010:80