services:
  portainer:
    image: portainer/portainer-ce

  feeddb:
    image: mongo

  feed.api:
    image: ${DOCKER_REGISTRY-}feedapi
    build:
      context: .
      dockerfile: Services/Feed/Feed.API/Dockerfile

  ocelotapigw:
     image: ocelotapigw
     build:
        context: .
        dockerfile: ApiGateways/Ocelot.Apigateway/Dockerfile

volumes:
  mongo_data:
  portainer_data:  