version: '3.4'

services:
  feeddb:
    container_name: feeddb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  feed.api:
    container_name: feed.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - DatabaseSettings__ConnectionString=mongodb://feeddb:27017
      - DatabaseSettings__DatabaseName=FeedDb
      - DatabaseSettings__PostsCollection=Posts
      - DatabaseSettings__CommentsCollection=Comments
      - DatabaseSettings__TagsCollection=Tags
      - DatabaseSettings__CommentLikesCollection=CommentLikes
      - DatabaseSettings__PostLikesCollection=PostLikes
      - DatabaseSettings__PostTagsCollection=PostTags
      - DatabaseSettings__SavedPostsCollection=SavedPosts
    depends_on:
      - feeddb
    ports:
      - "9000:80"