services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - 8080:8000
      - 9090:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  identitydb:
    container_name: identitydb
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=YourSecurePassword123
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/data/db
  
  feeddb:
    container_name: feeddb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - DatabaseSettings__ConnectionString=Server=identitydb;Database=IdentityDb;User Id=sa;Password=YourSecurePassword123;TrustServerCertificate=True;
    depends_on:
      - identitydb
    ports:
      - "9020:80"
  
  feed.api:
    container_name: feed.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - DatabaseSettings__ConnectionString=mongodb://feeddb:27017
      - DatabaseSettings__DatabaseName=FeedDb
      - DatabaseSettings__PostsCollection=Posts
      - DatabaseSettings__CommentsCollection=Comments
      - Services__Identity__BaseUrl=http://identity.api/api/v1/
    depends_on:
      - feeddb
    ports:
      - "9000:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - identity.api
      - feed.api
    ports:
      - 9010:80