services:
  portainer:
    image: portainer/portainer-ce

  identitydb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  feeddb:
    image: mongo
  
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  feed.api:
    image: ${DOCKER_REGISTRY-}feedapi
    build:
      context: .
      dockerfile: Services/Feed/Feed.API/Dockerfile

  ocelotapigw:
     image: ocelotapigw
     build:
        context: .
        dockerfile: ApiGateways/Ocelot.Apigateway/Dockerfile

volumes:
  mongo_data:
  sqlserver_data:
  portainer_data:  