services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - 8080:8000
      - 9090:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  feeddb:
    container_name: feeddb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  feed.api:
    container_name: feed.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - DatabaseSettings__ConnectionString=mongodb://feeddb:27017
      - DatabaseSettings__DatabaseName=FeedDb
      - DatabaseSettings__PostsCollection=Posts
      - DatabaseSettings__CommentsCollection=Comments
    depends_on:
      - feeddb
    ports:
      - "9000:80"
  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - feed.api
    ports:
      - 9010:80